sudo: false
language: ruby
cache: bundler

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - bundle update

script:
  - bundle exec rake spec

env:
  - rails=4.2.0
  - rails=5.0.0

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
