sudo: false
language: ruby
cache: bundler

before_install:
  - gem update bundler

before_script:
  - bundle update

script:
  - bundle exec rake spec

env:
  - rails=4.2.0
  - rails=5.0.0

rvm:
  - 2.1
  - 2.2.5
  - 2.3.1

matrix:
  exclude:
    - env: rails=5.0.0
      rvm: 2.1
