language: ruby
cache: bundler
sudo: false
arch:
  - amd64
  - ppc64le

before_install:
  - gem install bundler

before_script:
  - bundle exec rake migrate

script:
  - bundle exec rake spec

gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_master.gemfile
  - gemfiles/doorkeeper_master.gemfile

rvm:
  - 2.5
  - 2.6
  - 2.7

matrix:
  allow_failures:
    - gemfile: gemfiles/rails_master.gemfile
    - gemfile: gemfiles/doorkeeper_master.gemfile
    - gemfile: gemfiles/rails_master.gemfile
      arch: ppc64le
    - gemfile: gemfiles/doorkeeper_master.gemfile
      arch: ppc64le
