language: ruby
cache: bundler
sudo: false

before_install:
  - gem install bundler

before_script:
  - bundle exec rake migrate

script:
  - bundle exec rake spec

gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_master.gemfile
  - gemfiles/doorkeeper_master.gemfile

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7

matrix:
  exclude:
    - gemfile: gemfiles/rails_6.0.gemfile
      rvm: 2.4
    - gemfile: gemfiles/rails_master.gemfile
      rvm: 2.4
  allow_failures:
    - gemfile: gemfiles/rails_master.gemfile
    - gemfile: gemfiles/doorkeeper_master.gemfile
