name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    name: >-
      Ruby ${{ matrix.ruby }} (${{ matrix.gemfile }})
    env:
      CI: true

    runs-on: ${{ matrix.os }}
    if: |
      !(   contains(github.event.pull_request.title,  '[ci skip]')
        || contains(github.event.pull_request.title,  '[skip ci]'))
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        ruby:
          - 2.6
          - 2.7
          - '3.0'
          - '3.1'
          - head
        gemfile:
          - gemfiles/rails_5.0.gemfile
          - gemfiles/rails_5.2.gemfile
          - gemfiles/rails_6.0.gemfile
          - gemfiles/rails_6.1.gemfile
          - gemfiles/rails_7.0.gemfile
          - gemfiles/doorkeeper_master.gemfile
        exclude:
          - ruby: 3.0
            gemfile: gemfiles/rails_5_2.gemfile
          - ruby: 2.6
            gemfile: gemfiles/rails_7_0.gemfile
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        timeout-minutes: 10
        run: bundle exec rake spec
